### ISSUE TITLE
What is the license for this project

### ISSUE THREAD

**Issue by cyborgx7** [lufte/lona#1]
In most of the world, if you don't specify a license, by default it is all rights reserved.

If this is not your intention it would be nice if you could specify a license.

**Comment by lufte** [comment]
Hi there. Although it is not specified in the project's description, all javascript files have the GPLv3 header. I will include the license file soon, thank's for the reminder.

**Comment by cyborgx7** [comment]
I completely forgot about that. I looked at a fair bit of your code not too long ago, as well. Sorry for bothering you.

I really like your game.
