### ISSUE TITLE
Make the whole screen clickable on mobile.

### ISSUE THREAD

**Issue by Zykino** [lufte/lona#10]
On a 16/9 portrait screen there is a dead zone at the bottom. I would like to click here to play, so I don't hide the game with my fingers… and I click in a more natural one hand position.

Also is it possible to make the retry button bigger? I select it way more often than I want to.

By the way your game is driving me mad! It illustrate so well the "make your first game like a classic one with a twist" advice. I don't find good ideas but Lona is a perfect example. And it's fun to play and minimalist.

**Comment by lufte** [comment]
Hey, thanks for your kind words. It's always nice to see people that like my little game even after so many years since I wrote it.

Your request makes a lot of sense, I'll try to work it out.

**Comment by lufte** [comment]
Hi. Could you try the online version at https://lufte.github.io/lona and check if you can click on the whole screen now?

**Comment by Zykino** [comment]
I don't have the same space when I use a browser than with the app. The URL bar on top of the browser is close to the exact size of the free space in the app. I tried to click in the 5/10px still at the bottom and it worked... but fingers on this little space I'm not certain I aimed it exactly.

**Comment by lufte** [comment]
Oh I understand. Well, no problem, I tried it in my desktop browser and it was definitely working after the fix. Let me know once you get the new version from fdroid.

**Comment by lufte** [comment]
Ok now you should be able to download the latest version from F-Droid. Let me know if the issue is fixed. If not, you'll have to wait another two months 😄

**Comment by Zykino** [comment]
Yep, it's working well, thank you !
