### ISSUE TITLE
When will translations be applied?

### ISSUE THREAD

**Issue by Porrumentzio** [lufte/lona#20]
Both on web version and Android webapp

**Comment by lufte** [comment]
Hi @Porrumentzio , thanks for the ping. I'll take care of it during the weekend :)

**Comment by lufte** [comment]
Well, the web version is updated. F-Droid should pick up the new [tag](https://github.com/lufte/lona/releases/tag/v1.0.2) automatically and build a new version, I'm not sure how long would that take though.
