### ISSUE TITLE
Screenshots for F-Droid

### ISSUE THREAD

**Issue by mondlicht-und-sterne** [lufte/lona#23]
You can add Screenshots for F-Droid, too, if you want.
https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/
https://gitlab.com/snippets/1895688
That was simply information about what is still possible. You would then only have to enter the screenshots in fastlane. This is just one way that you can also add screenshots to the app view if you can. If you added screenshots (then F-Droid is happy) and if you can't add any -> then you can close the issue because it was only an info. Thank you that your app is available in
fdroid. Very much for your attention.

it is only information.

**Comment by lufte** [comment]
Hey! This is a good idea. Would you be willing to make a pull request to address this? Here's a nice screenshot you can use with a high score. Maybe you can add a couple more.
![Screen Shot 2021-04-25 at 13 49 25](https://user-images.githubusercontent.com/7890579/116005949-9e79bb00-a5df-11eb-83f1-392a43777aaa.png)
