### ISSUE TITLE
Configure params (speed, size, etc)

### ISSUE THREAD

**Issue by nitrocode** [lufte/lona#24]
It would be nice to configure the following parameters

- lona speed
- lona size
- ball point size
- size of boundary
- others?

**Comment by lufte** [comment]
Hi nitrocode! You know, I'm not really adding new features to this game anymore, but I keep the repository open for bugs and translations. I've thought about this idea before but it would make high scores meaningless.

Of course, you're free to implement this (and you should!) in a fork of yours. Most of those settings are clearly defined as constants in the source code so it shouldn't be hard to achieve this.
