### ISSUE TITLE
Android port using Cordova

### ISSUE THREAD

**Issue by cyborgx7** [lufte/lona#5]
After the death of Firefox OS I went back to Android but I miss this game. I'm going to start work on embedding this game in https://cordova.apache.org/ and then try to get it onto f-droid.

This issue is to let you know. If you have any notes on that effort, I'd be glad to hear them.

**Comment by lufte** [comment]
Hey sure, be my guest. I'm glad to know someone still remembers this game :smile: 

I remember making an app out of this game with Cordova back in the day and it worked out of the box without any kind of extra work, I hope that's still the case.

Let me know when it's published :+1:

**Comment by cyborgx7** [comment]
I have it compiled as an apk now. It has some weird behaviours right now, like registering a turn event on both the press as well as the release. And holding selects the score text. Need to do some debugging there. But at least it is running on my phone again.

Might not be as easy as I had hoped to get it into f-droid. Seems like they have troubles getting apps that rely on cordova to build propperly.

And of course I remember this game. It's one of my goto examples when I have conversations about game design with people. I've talked and thought a lot about your little game over the years.

**Comment by lufte** [comment]
> I have it compiled as an apk now. It has some weird behaviours right now, like registering a turn event on both the press as well as the release. And holding selects the score text. Need to do some debugging there. But at least it is running on my phone again.
Ah, I think I recall that issue now that you mention it.

>Might not be as easy as I had hoped to get it into f-droid. Seems like they have troubles getting apps that rely on cordova to build properly in their build environment.
This would be a shame. Let me know if I can help you in some way with this.

>And of course I remember this game. It's one of my goto examples when I have conversations about game design with people. I've talked and thought a lot about your little game over the years.
Oh stop it, you're making me blush :blush:

**Comment by Bubu** [comment]
It's now published. (f-droid website is not yet updated but can be downloaded in the client.)

What I don't quite understand is why this app needs internet permission? Afaik it shouldn't actually need access to the inernet?

**Comment by lufte** [comment]
You're right, it doesn't need to. That's probably the default Cordova permission, I should look into that.

Thanks for the heads up.

**Comment by lufte** [comment]
Published https://f-droid.org/en/packages/io.github.lufte.lona

**Comment by cyborgx7** [comment]
Just found this on f-droid. Really glad this got taken care off when I wasn't able to.

Cheers.
